# Generated by Django 6.0.5 on 2026-05-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='branch',
        ),
    ]
