# Generated by Django 6.0.5 on 2026-05-30 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_service_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQueueNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_numbers', to='salon.branch')),
            ],
            options={
                'verbose_name': 'رقم الدور اليومي',
                'verbose_name_plural': 'أرقام الدور اليومية',
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
