# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_consumptioninvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المصروف')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='salon.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('out', 'مصروف'), ('return', 'مرتد')], default='out', max_length=10, verbose_name='نوع السند')),
                ('serial_number', models.PositiveIntegerField(default=0, verbose_name='المسلسل')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('bank', 'بنك')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers', to='salon.bank', verbose_name='البنك')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_vouchers', to='salon.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='salon.expensetype', verbose_name='المصروف')),
            ],
            options={
                'verbose_name': 'Expense Voucher',
                'verbose_name_plural': 'Expense Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensevoucher',
            constraint=models.UniqueConstraint(fields=('branch', 'voucher_type', 'serial_number'), name='unique_branch_expense_voucher_serial'),
        ),
    ]
