# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_expensetype_expensevoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(default='صالون برو', max_length=100, verbose_name='اسم الصالون')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('logo', models.ImageField(blank=True, upload_to='salon/logo/', verbose_name='الشعار')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة')),
                ('receipt_size', models.CharField(default='80mm', max_length=10, verbose_name='نمط الطباعة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الضريبة %')),
                ('auto_backup', models.BooleanField(default=False, verbose_name='نسخ احتياطي')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon Settings',
                'verbose_name_plural': 'Salon Settings',
            },
        ),
    ]
