# Generated by Django 5.2.15 on 2026-06-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0016_employee_invoice_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_invoice',
            field=models.ForeignKey(blank=True, db_column='reference_invoice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='salon.purchaseinvoice', verbose_name='فاتورة مشتريات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_bookings',
            field=models.BooleanField(default=False, verbose_name='Can Access Bookings'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_customers',
            field=models.BooleanField(default=False, verbose_name='Can Access Customers'),
        ),
    ]
