# Generated by Django 5.2.15 on 2026-06-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0017_align_model_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('void', 'إلغاء')], max_length=10, verbose_name='العملية')),
                ('entity_type', models.CharField(max_length=50, verbose_name='النوع')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='المعرف')),
                ('entity_label', models.CharField(max_length=255, verbose_name='الوصف')),
                ('details', models.TextField(blank=True, default='', verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='salon.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل حركة',
                'verbose_name_plural': 'سجل الحركات',
                'ordering': ['-created_at'],
            },
        ),
    ]
