# Generated by Django 5.2.15 on 2026-06-20 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0018_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('cash_to_bank', 'نقدية → بنك'), ('bank_to_cash', 'بنك → نقدية')], max_length=20, verbose_name='الاتجاه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='بيان')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('serial_number', models.PositiveIntegerField(default=0, verbose_name='المسلسل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_transfers', to='salon.bank', verbose_name='البنك')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transfers', to='salon.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transfers', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'تحويل حساب',
                'verbose_name_plural': 'تحويلات الحسابات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'serial_number'), name='unique_branch_transfer_serial')],
            },
        ),
    ]
