# Generated by Django 5.2.15 on 2026-06-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_account_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_booking_queue',
            field=models.BooleanField(default=True, verbose_name='Queue Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_booking_vip',
            field=models.BooleanField(default=True, verbose_name='VIP Booking'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_services',
            field=models.BooleanField(default=False, verbose_name='Can Delete Services'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_expense_out',
            field=models.BooleanField(default=True, verbose_name='Expense Out'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_expense_return',
            field=models.BooleanField(default=True, verbose_name='Expense Return'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_expense_types',
            field=models.BooleanField(default=True, verbose_name='Expense Types'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_inv_consumption',
            field=models.BooleanField(default=True, verbose_name='Inventory Consumption'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_inv_items',
            field=models.BooleanField(default=True, verbose_name='Inventory Items'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_inv_purchase',
            field=models.BooleanField(default=True, verbose_name='Inventory Purchase'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_inv_report',
            field=models.BooleanField(default=True, verbose_name='Inventory Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_inv_totals',
            field=models.BooleanField(default=True, verbose_name='Inventory Totals'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_report_activity',
            field=models.BooleanField(default=True, verbose_name='Activity Log'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_report_statement',
            field=models.BooleanField(default=True, verbose_name='Account Statement'),
        ),
    ]
