# Generated by Django 5.2.15 on 2026-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0020_granular_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_booking_queue',
            field=models.BooleanField(default=False, verbose_name='Queue Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_booking_vip',
            field=models.BooleanField(default=False, verbose_name='VIP Booking'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_expense_out',
            field=models.BooleanField(default=False, verbose_name='Expense Out'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_expense_return',
            field=models.BooleanField(default=False, verbose_name='Expense Return'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_expense_types',
            field=models.BooleanField(default=False, verbose_name='Expense Types'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_expenses',
            field=models.BooleanField(default=False, verbose_name='Can Access Expenses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_inv_consumption',
            field=models.BooleanField(default=False, verbose_name='Inventory Consumption'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_inv_items',
            field=models.BooleanField(default=False, verbose_name='Inventory Items'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_inv_purchase',
            field=models.BooleanField(default=False, verbose_name='Inventory Purchase'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_inv_report',
            field=models.BooleanField(default=False, verbose_name='Inventory Report'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_inv_totals',
            field=models.BooleanField(default=False, verbose_name='Inventory Totals'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_inventory',
            field=models.BooleanField(default=False, verbose_name='Can Access Inventory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_pos',
            field=models.BooleanField(default=False, verbose_name='Can Access POS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_report_activity',
            field=models.BooleanField(default=False, verbose_name='Activity Log'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_report_statement',
            field=models.BooleanField(default=False, verbose_name='Account Statement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_reports',
            field=models.BooleanField(default=False, verbose_name='Can Access Reports'),
        ),
    ]
