# Generated by Django 5.2.15 on 2026-06-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0021_permission_defaults_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='كلمة المرور (مرئية)'),
        ),
    ]
